
const { Pool } = require("pg");
const dotenv = require("dotenv");

dotenv.config();

// =========================================================
// DATABASE CONNECTION
// =========================================================

if (!process.env.DATABASE_URL) {
  console.error("❌ DATABASE_URL is missing.");
  console.error("Please add DATABASE_URL in Render Environment.");
}

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: process.env.DATABASE_URL
    ? { rejectUnauthorized: false }
    : false,
});

// =========================================================
// DATABASE INITIALIZATION
// =========================================================

async function initDatabase() {
  // =======================================================
  // STOCK TABLE
  // =======================================================

  await pool.query(`
    CREATE TABLE IF NOT EXISTS stock (
      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

      medicine TEXT,
      company TEXT,
      batch TEXT,
      barcode TEXT,
      supplier TEXT,
      "supplierMobile" TEXT,

      quantity DOUBLE PRECISION DEFAULT 0,
      rate DOUBLE PRECISION DEFAULT 0,
      mrp DOUBLE PRECISION DEFAULT 0,
      "saleRate" DOUBLE PRECISION DEFAULT 0,

      expiry TEXT,

      "gstType" TEXT,
      "gstPercent" DOUBLE PRECISION DEFAULT 0,
      "purchaseRateWithGST" DOUBLE PRECISION DEFAULT 0,
      "purchaseAmount" DOUBLE PRECISION DEFAULT 0,

      "createdAt" TEXT,
      "updatedAt" TEXT
    )
  `);

  // =======================================================
  // BILLS TABLE
  // =======================================================

  await pool.query(`
    CREATE TABLE IF NOT EXISTS bills (
      id TEXT PRIMARY KEY,

      "billNo" TEXT,

      customer TEXT,
      "customerName" TEXT,
      "customerMobile" TEXT,
      mobile TEXT,

      items TEXT,

      "totalItems" DOUBLE PRECISION DEFAULT 0,
      "totalQuantity" DOUBLE PRECISION DEFAULT 0,

      "discountPercent" DOUBLE PRECISION DEFAULT 0,
      "discountAmount" DOUBLE PRECISION DEFAULT 0,

      subtotal DOUBLE PRECISION DEFAULT 0,
      "billTotal" DOUBLE PRECISION DEFAULT 0,
      total DOUBLE PRECISION DEFAULT 0,
      "totalAmount" DOUBLE PRECISION DEFAULT 0,

      "previousAdvance" DOUBLE PRECISION DEFAULT 0,
      "advanceAdjusted" DOUBLE PRECISION DEFAULT 0,
      "advanceUsed" DOUBLE PRECISION DEFAULT 0,
      "billAfterAdvance" DOUBLE PRECISION DEFAULT 0,

      "paymentReceived" DOUBLE PRECISION DEFAULT 0,
      "receivedAmount" DOUBLE PRECISION DEFAULT 0,

      "billPaid" DOUBLE PRECISION DEFAULT 0,
      "paidNow" DOUBLE PRECISION DEFAULT 0,

      jama DOUBLE PRECISION DEFAULT 0,
      paid DOUBLE PRECISION DEFAULT 0,
      "paidAmount" DOUBLE PRECISION DEFAULT 0,

      "paidAtBill" DOUBLE PRECISION DEFAULT 0,
      "receivedAtBill" DOUBLE PRECISION DEFAULT 0,

      "bakiUdhari" DOUBLE PRECISION DEFAULT 0,
      "pendingAmount" DOUBLE PRECISION DEFAULT 0,
      "creditAmount" DOUBLE PRECISION DEFAULT 0,

      credit INTEGER DEFAULT 0,

      advance DOUBLE PRECISION DEFAULT 0,
      "advanceAdded" DOUBLE PRECISION DEFAULT 0,
      "advanceBalance" DOUBLE PRECISION DEFAULT 0,
      "remainingAdvance" DOUBLE PRECISION DEFAULT 0,

      "paymentType" TEXT,

      date TEXT,
      "billDate" TEXT,

      "createdAt" DOUBLE PRECISION DEFAULT 0
    )
  `);

  console.log("==========================================");
  console.log("✅ Neon PostgreSQL Database Ready");
  console.log("✅ STOCK table ready");
  console.log("✅ BILLS table ready");
  console.log("==========================================");
}

// =========================================================
// EXPORT
// =========================================================

module.exports = {
  pool,
  initDatabase,
};